15-rails-associations-and-nested-forms/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'books/index'
  get 'books/show'
  get 'books/new'
  get 'books/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
  resources :authors
end

15-rails-associations-and-nested-forms/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author

  def author_attributes=(attributes)
    self.author = Author.find_or_create_by(attributes)
  end
end

15-rails-associations-and-nested-forms/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
    @book.author = Author.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  private

  def set_book
    unless @book = Book.find_by_id(params[:id])
      redirect_to books_path
    end
  end

  def book_params
    params.require(:book).permit(:title, author_attributes: [:name])
  end
end

15-rails-associations-and-nested-forms/app/views/books/index.html.erb
<h1>Books Index</h1>

<ul>
<% @books.each do |book| %>
    <li><%= link_to book.title, book_path(book) %></li>
<% end %>
</ul>

<%= link_to :'New Book', new_book_path %>

15-rails-associations-and-nested-forms/app/views/books/new.html.erb
<h1>Create New Book</h1>

<%= form_for @book do |f| %>
    <p>
	<%= f.label :title %>
	<%= f.text_field :title, :id => 'foo', :foo => 'bar' %>

    </p>
    <p>
	<%= f.fields_for :author do |ff| %>
	    <%= ff.label :name %>
	    <%= ff.text_field :name %>
	<% end %>
    </p>
    <p>
	<%= f.submit %>
    </p>
<% end %>

15-rails-associations-and-nested-forms/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>By <%= @book.author.name %></p>