16-partials-and-layouts/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'genres/index'
  get 'authors/index'
  get 'books/index'
  get 'books/create'
  get 'books/new'
  get 'books/edit'
  get 'books/update'
  resources :books, only: %i[index new create edit update destory]
  resources :authors, only: [:index]
  resources :genres, only: [:index]
end

16-partials-and-layouts/app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :genres, through: :books

  validates :name, presence: true, uniqueness: true
end

16-partials-and-layouts/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :genre
  belongs_to :author
  validates :title, presence: true, uniqueness: { scope: :author }

  def author_attributes=(args)
    self.author = Author.find_or_create_by(args)
  end

  def genre_attributes=(args)
    self.genre = Genre.find_or_create_by(args)
  end
end

16-partials-and-layouts/app/models/genre.rb
class Genre < ApplicationRecord
  has_many :books
  has_many :authors, through: :books
  validates :name, presence: true, uniqueness: true
end

16-partials-and-layouts/app/controllers/.#books_controller.rb
jake@localhost.localdomain.2826932:1579538482

16-partials-and-layouts/app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def create
    byebug
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_url
    else
      @errors = @book.errors.full_messages
      render :new
    end
  end

  def new
    @book = Book.new
    @book.author = Author.new
    @book.genre = Genre.new
  end

  def edit
    unless @book = Book.find_by_id(params[:id])
      @errors = ["Book not found"]
      redirect_to books_url
    end
  end

  def update
  end

  def book_params
    params.require(:book).permit(:title, author_attributes: [:name], genre_attributes: [:name])
  end
end

16-partials-and-layouts/app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end
end

16-partials-and-layouts/app/helpers/genres_helper.rb
module GenresHelper
end

16-partials-and-layouts/app/views/authors/.#index.html.erb
jake@localhost.localdomain.2826932:1579538482

16-partials-and-layouts/app/views/authors/index.html.erb
<h1>Authors</h1>

<% @authors.each do |author| %>
    <h2><%= author.name %></h2>
    <%= render partial: 'books/all_books', locals: {books: author.books} %>
<% end %>

16-partials-and-layouts/app/views/genres/index.html.erb
<h1>Genres</h1>

<% @genres.each do |genre| %>
    <h2><%= genre.name %></h2>
    <%= render partial: 'books/all_books', locals: {books: genre.books} %>
<% end %>

16-partials-and-layouts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PartialsAndLayouts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
      <nav>
	  <%= link_to :authors, authors_path %>
	  <%= link_to :genres, genres_path %>
	  <%= link_to :books, books_path %>
      </nav>
      <% if @errors %>
	  <ul>
	      <% @errors.each do |msg| %>
		  <li><%= msg %></li>
		  <% end %>
	  </ul>
	  <% end %>
    <%= yield %>
  </body>
</html>