17-routing-in-rails-nested-routes/config/routes.rb
Rails.application.routes.draw do
  get '/authors/:author_id/books/:id/delete', to: 'books#destroy', as: 'author_book_delete'
  resources :authors, only: [:index] do
    resources :books
  end

  resources :books, only: [:new, :create]
end

17-routing-in-rails-nested-routes/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end
end

17-routing-in-rails-nested-routes/app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_author, except: [:new, :create]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = @author.books
  end

  def new
    @book = Book.new
    if @author = Author.find_by_id(params[:author_id])
      @path = author_books_path(@author)
    else
      @author = Author.new
      @path = books_path
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to author_book_url(@author, @book)
    else
      render :new
    end
  end

  def show
    @book = Book.find_by_id(params[:id])
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to author_book_url(@author, @book)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to author_books_url(@author)
  end

  private

  def set_author
    unless @author = Author.find_by_id(params[:author_id])
      redirect_to authors_path
    end
  end

  def set_book
    unless @book = Book.find_by_id(params[:id])
      redirect_to author_books(@author)
    end
  end

  def book_params
    params.require(:book).permit(:title, author_attributes: [:name, :id])
  end
end

17-routing-in-rails-nested-routes/app/helpers/books_helper.rb
module BooksHelper
end

17-routing-in-rails-nested-routes/app/views/books/_form.html.erb
<%= form_for(book, url: url) do |f| %>
    <p>
	<%= f.label :title, :'Title: ' %>
	<%= f.text_field :title %>
    </p>
    <p>
	<%= fields_for :author, author do |ff| %>
	    <%= ff.label :name, :'Author Name' %>
	    <%= ff.text_field :name %>
	<% end %>
    </p>
    <%= f.submit %>
<% end %>

17-routing-in-rails-nested-routes/app/views/books/edit.html.erb
<h1>Edit <%= @book.title %></h1>
<%= render partial: 'form', locals: { book: @book, author: @author, url: author_book_path(@author, @book) } %>

17-routing-in-rails-nested-routes/app/views/books/index.html.erb
<h1><%= @author.name %></h1>

<ul>
    <% @books.each do |book| %>
	<li><%= link_to book.title, author_book_path(book.author, book) %></li>
    <% end %>
</ul>

<%= link_to 'Create New Book', new_author_book_path(@author) %>

17-routing-in-rails-nested-routes/app/views/books/new.html.erb
<h1>Create new Book</h1>

<%= render partial: 'form', locals: { book: @book, author: @author, url: @path } %>

17-routing-in-rails-nested-routes/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p>By <%= link_to @book.author.name, author_books_path(@book.author, @book) %></p>
<%= link_to :'Edit Book', edit_author_book_path(@book.author, @book) %>
<%= link_to :'Delete Book', author_book_delete_path(@book.author, @book), method: :delete %>